### ISSUE TITLE
mark default as the exhaustive

### ISSUE THREAD

**Issue by egonelbre** [loov/enumcheck#3]
Ensure that default case wouldn't report an error message.

Question: Should there be an option to mark default cases as non-exhaustive?

**Comment by empijei** [comment]
What do you think would be the use case? I think it would be very nice to have some way to mark the default as "this should never happen" but still have it.

**Comment by egonelbre** [comment]
Ah, sorry, should make it slightly clearer:

The behavior would be that the "default" case doesn't mark it as exhaustive. So in some cases you might want to ensure that all the cases are always handled and the default case is the backup.

The behavior would be something like:

```
type Letter byte // checkenum: non-exhaustive-default

const (
	Alpha = Letter('a')
	Beta = Letter('b')
)


var x Letter
switch x { // error: missing case Beta
case Alpha:
	fmt.Println("alpha")
default:
	fmt.Println("unexpected", x)
}
```

and the usual behavior:

```
type Letter byte // checkenum

const (
	Alpha = Letter('a')
	Beta = Letter('b')
)


var x Letter
switch x { // no error, because the default case will treat it as exhaustive handling
case Alpha:
	fmt.Println("alpha")
default:
	fmt.Println("unexpected", x)
}
```

**Comment by egonelbre** [comment]
alternatively the flag could be `checkenum: exhaustive-default-case`, such that the default behavior requires to handle all the cases.

**Comment by egonelbre** [comment]
I currently made it to allow default case, but it'll still complain about missing cases.

**Comment by egonelbre** [comment]
For now, I made it complain about missing default. To suppress the warning, it's easy to add an empty default case.

I'll add a separate comment for `//enumcheck:ignore` which allows to ignore errors on the specific lines.
